export const STARKNET_TRANSACTION_PROVER_COMPONENT_VERSION = "PRIVACY-0.14.3-RC.2";
export const STARKNET_TRANSACTION_PROVER_API_VERSION = "0.10.3-rc.2";
export const STARKNET_DISCOVERY_SERVICE_COMPONENT_VERSION = "PRIVACY-0.14.3-RC.2";
export const STARKNET_PROOF_INTERCEPTOR_COMPONENT_VERSION = "PRIVACY-0.14.3-RC.6";
